### ISSUE TITLE
Assigning the message to a variable should be allowed

### ISSUE THREAD

**Issue by morazow** [exasol/error-code-crawler-maven-plugin#61]
Assigning an error message (with `.toString()` call) to a variable should be allowed. Only the builder must not be assigned.

Context: https://github.com/exasol/error-reporting-java/pull/32

**Comment by pj-spoelders** [comment]
It works when you use the helper method, you don't get these errors then: 
Normally you wouldn't be able to use the c'tor because it's not public, like you do for these tests.

Also, using the error parser on the actual library that defines the parsed errors doesn't make a whole lot of sense to me, neither does checking the actual tests since these errors are supposed to be the customer facing ones. There's no point having these in tests at all. We need to discuss this.
